### ISSUE TITLE
nested object of type IEnumerable

### ISSUE THREAD

**Issue by ltemimi** [hughbe/excel-mapper#66] opened 2021-02-23 14:57 UTC
Hi
Great that Excel-Mapper handles nested objects
Any idea on how to handle a nested object when it is a collection (i.e. a collection of a nested object such as "IEnumerable<Student>" one teacher has many students?
Thanks
Laz

**Comment by hughbe** [comment] 2021-02-23 15:32
Is this similar to https://github.com/hughbe/excel-mapper/issues

Could you share your excel column structure and c# class structure so I can better understand?

**Comment by ltemimi** [comment] 2021-02-23 15:42
Hi
Yes it is exactly the same issue
Excel Columns
IpAddress | Rack | Slot | Port | Timeout | ControllerType | Name | Enable | ScanTime | LoggingFrequency | PlcAddress | FriendlyName | Description | PlcDataType | Units | PlcAddress2 | FriendlyName3 | Description4 | PlcDataType5 | Units6 | PlcAddress7 | FriendlyName8 | Description9 | PlcDataType10 | Units11 | PlcAddress12 | FriendlyName13 | Description14 | PlcDataType15 | Units16
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Nested object structure
```

public enum ControllerSelection
    {
        None,
        Logix,
        Micro,
        AbLink,
        S1500,
        [UsedImplicitly] S1200,
        [UsedImplicitly] S200,
        [UsedImplicitly] S200Smart,
        [UsedImplicitly] S300,
        [UsedImplicitly] S400
    }
	
	 public sealed class TagInfo : ITagInfo
    {
        public string PlcAddress { get; internal init; }
        public string Description { get; internal init; }
        public string PlcDataType { get; internal init; }
        public int Length { get; } = DefaultLength;
        public object Value { get; set; }
        public string Units { get; internal init; }
        public string FriendlyName { get; internal init; }
    }
	
	public sealed class LogEvent : ILogEvent
    {
        public string Name { get; set; } = string.Empty;
        public bool Enable { get; set; }
        public int ScanTime { get; set; }

        public ITagInfo RunId { get; set; } = new TagInfo
        {
            PlcAddress = string.Empty,
            PlcDataType = "string",
            Value = ""
        };

        public ITagInfo TagsLogEnable { get; set; } = new TagInfo
        {
            PlcAddress = string.Empty,
            PlcDataType = "bool",
            Value = "false"
        };

        public ITagInfo TagsLoggedAck { get; set; } = new TagInfo
        {
            PlcAddress = string.Empty,
            PlcDataType = "bool",
            Value = "false"
        };

        public int LoggingFrequency { get; set; } = 2000;
        public ICollection<TagInfo> Tags { get; set; } = new List<TagInfo>();
    }
	
	
	 public sealed class ControllerInfo : IControllerInfo
    {
        public string IpAddress { get; internal init; }
        public byte Rack { get; internal init; }
        public byte Slot { get; internal init; }
        public int Port { get; internal init; }
        public int Timeout { get; internal init; }
        public ControllerSelection ControllerType { get; internal init; }

        /// <inheritdoc />
        public ICollection<LogEvent> LogEvents { get; set; }
    }
```

**Comment by ltemimi** [comment] 2021-02-23 18:08
Hi

Thanks I understand, I have broken up the excel sheet and used linq join (it works similar to your solution)

I have a question. : Can I read data from specific ranges in a sheet that would help no end 

regards
Laz

**Comment by hughbe** [comment] 2021-02-23 18:10
Have you seen the `ExcelSheet.ReadRows<T>(int startIndex, int count)` API?

**Comment by hughbe** [comment] 2021-02-23 18:11
Also closing this as a duplicate of #64. I'm going to do some thinking about how this API would look like

**Closed** 2021-02-23 18:11 UTC
